### ISSUE TITLE
Error on parsing ldif 

### ISSUE THREAD

**Issue by mareban** [stufus/ADOffline#3]
Hello,

Nice tool, but it doesn't work for me !!!

Is it something to have with the parsing of the ldif or a bug or something else ?

Thanks for your help.

[11/Feb/17 15:11:54] Creating database: Traceback (most recent call last):
  File "./adoffline.py", line 450, in <module>
    create_views(sql)
  File "./adoffline.py", line 143, in create_views
    CASE WHEN (sAMAccountType==0x7fffffff) THEN 1 ELSE 0 END AS SAM_ACCOUNT_TYPE_MAX FROM raw_users''')
sqlite3.OperationalError: unrecognized token: "0x00000001"

**Comment by EtengoTHA** [comment]
You have to make sure that you use at least SQLite 3.8 for this to work. Else the hex literals used in the script will not work.
